### ISSUE TITLE
[JENKINS-62544] BFA: Exception after update to 1.26.0

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/build-failure-analyzer-plugin#373]
<p>After update of all plugins to their latest versions (incl. the BFA plugin), no known failure causes are shown anymore under "Failure Cause Management". Instead, that page shows a red error text:</p>

<pre>
Could not fetch causes: java.lang.reflect.InvocationTargetException</pre>
<p>We use MongoDB to store the known error cases.</p>

<p>The Jenkins log has a complete stack trace:</p>

<pre>
Jun 03, 2020 1:14:49 PM SEVERE com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner scan
Could not scan build SomeJob #1234
java.lang.NoSuchMethodError: <span class="code-quote">'java.lang.reflect.Type com.fasterxml.jackson.databind.introspect.Annotated.getGenericType()'</span>
	at org.mongojack.internal.MongoAnnotationIntrospector.getTypeForAnnotated(MongoAnnotationIntrospector.java:81)
	at org.mongojack.internal.MongoAnnotationIntrospector.findDeserializer(MongoAnnotationIntrospector.java:97)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findDeserializer(AnnotationIntrospectorPair.java:665)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDeserializerFromAnnotation(BasicDeserializerFactory.java:2092)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.constructCreatorProperty(BasicDeserializerFactory.java:1019)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addExplicitPropertyCreator(BasicDeserializerFactory.java:634)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addExplicitAnyCreator(BasicDeserializerFactory.java:661)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:411)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:283)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:220)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:491)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4669)
Caused: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor762.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mongojack.internal.util.JacksonAccessor.invoke(JacksonAccessor.java:149)
Caused: java.lang.RuntimeException
	at org.mongojack.internal.util.JacksonAccessor.invoke(JacksonAccessor.java:153)
	at org.mongojack.internal.util.JacksonAccessor.findDeserializer(JacksonAccessor.java:44)
	at org.mongojack.internal.util.IdHandlerFactory.getIdHandlerForProperty(IdHandlerFactory.java:40)
	at org.mongojack.JacksonDBCollection.<init>(JacksonDBCollection.java:138)
	at org.mongojack.JacksonDBCollection.wrap(JacksonDBCollection.java:236)
	at com.sonyericsson.jenkins.plugins.bfa.db.MongoDBKnowledgeBase.getJacksonCollection(MongoDBKnowledgeBase.java:1099)
	at com.sonyericsson.jenkins.plugins.bfa.db.MongoDBKnowledgeBase.initCache(MongoDBKnowledgeBase.java:212)
	at com.sonyericsson.jenkins.plugins.bfa.db.MongoDBKnowledgeBase.getCauses(MongoDBKnowledgeBase.java:224)
	at com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner.scan(BuildFailureScanner.java:189)
	at com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner.scanIfNotScanned(BuildFailureScanner.java:165)
	at com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner.doScan(BuildFailureScanner.java:141)
	at com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner.onCompleted(BuildFailureScanner.java:121)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
	at hudson.model.Run.execute(Run.java:1860)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
</pre>
<p>We also tried to downgrade the plugin to 1.24.1 again, but that didn't help.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dhs">dhs</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62544" target="_blank">BFA: Exception after update to 1.26.0</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/t_westling.jpg" title="t_westling's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=t_westling">t_westling</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: build-failure-analyzer-plugin
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2020-06-15T07:28:56+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-12-07
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After update of all plugins to their latest versions (incl. the BFA plugin), no known failure causes are shown anymore under "Failure Cause Management". Instead, that page shows a red error text:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Could not fetch causes: java.lang.reflect.InvocationTargetException</pre>
</div></div>
<p>We use MongoDB to store the known error cases.</p>

<p>The Jenkins log has a complete stack trace:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Jun 03, 2020 1:14:49 PM SEVERE com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner scan
Could not scan build SomeJob #1234
java.lang.NoSuchMethodError: <span class="code-quote">'java.lang.reflect.Type com.fasterxml.jackson.databind.introspect.Annotated.getGenericType()'</span>
	at org.mongojack.internal.MongoAnnotationIntrospector.getTypeForAnnotated(MongoAnnotationIntrospector.java:81)
	at org.mongojack.internal.MongoAnnotationIntrospector.findDeserializer(MongoAnnotationIntrospector.java:97)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findDeserializer(AnnotationIntrospectorPair.java:665)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDeserializerFromAnnotation(BasicDeserializerFactory.java:2092)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.constructCreatorProperty(BasicDeserializerFactory.java:1019)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addExplicitPropertyCreator(BasicDeserializerFactory.java:634)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addExplicitAnyCreator(BasicDeserializerFactory.java:661)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:411)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:283)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:220)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:491)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4669)
Caused: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor762.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mongojack.internal.util.JacksonAccessor.invoke(JacksonAccessor.java:149)
Caused: java.lang.RuntimeException
	at org.mongojack.internal.util.JacksonAccessor.invoke(JacksonAccessor.java:153)
	at org.mongojack.internal.util.JacksonAccessor.findDeserializer(JacksonAccessor.java:44)
	at org.mongojack.internal.util.IdHandlerFactory.getIdHandlerForProperty(IdHandlerFactory.java:40)
	at org.mongojack.JacksonDBCollection.&lt;init&gt;(JacksonDBCollection.java:138)
	at org.mongojack.JacksonDBCollection.wrap(JacksonDBCollection.java:236)
	at com.sonyericsson.jenkins.plugins.bfa.db.MongoDBKnowledgeBase.getJacksonCollection(MongoDBKnowledgeBase.java:1099)
	at com.sonyericsson.jenkins.plugins.bfa.db.MongoDBKnowledgeBase.initCache(MongoDBKnowledgeBase.java:212)
	at com.sonyericsson.jenkins.plugins.bfa.db.MongoDBKnowledgeBase.getCauses(MongoDBKnowledgeBase.java:224)
	at com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner.scan(BuildFailureScanner.java:189)
	at com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner.scanIfNotScanned(BuildFailureScanner.java:165)
	at com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner.doScan(BuildFailureScanner.java:141)
	at com.sonyericsson.jenkins.plugins.bfa.BuildFailureScanner.onCompleted(BuildFailureScanner.java:121)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
	at hudson.model.Run.execute(Run.java:1860)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
</pre>
</div></div>
<p>We also tried to downgrade the plugin to 1.24.1 again, but that didn't help.</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins 2.190.1, Ubuntu 18.04 LTS</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>jtancer:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62544?focusedId=392536&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-392536">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>This issue has already been reported.</p>

<p>See this ticket - <a href="https://issues.jenkins-ci.org/browse/JENKINS-62214" class="external-link" target="_blank" rel="nofollow noopener">https://issues.jenkins-ci.org/browse/JENKINS-62214</a></p>
</pre>
</details>

</ul>
</details>

<p>This issue has already been reported.</p>

<p>See this ticket - <a href="https://issues.jenkins-ci.org/browse/JENKINS-62214" class="external-link" target="_blank" rel="nofollow noopener">https://issues.jenkins-ci.org/browse/JENKINS-62214</a></p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `duplicates` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/62214">JENKINS-62214</a>]</i>
